name: Build

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v3
        with:
          pull: true
          push: true
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ github.repository }}:cache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ github.repository }}:cache
          tags: ${{ env.REGISTRY }}/${{ github.repository }}:latest
